HX711: Remove unused virtual destructor
The virtual destructor sometimes caused weird linker errors:

----
tools/compile_test.py CompileTest.test_max_config_fc2x0

HX711.cpp.obj: In function `HX711::power_up()':
Arduino_Pedelec_Controller/HX711.cpp:134: undefined reference to `operator delete(void*, unsigned int)
----